name: E2E checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "LICENSE"
      - "**/.gitignore"
      - "**.md"
      - "**.adoc"
      - "*.txt"
      - "docsimg/**"
      - ".ci/jenkins/**"

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: End-to-end tests
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
      
    - name: Run tests
      run: |
        make test-e2e