name: E2E checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "LICENSE"
      - "**/.gitignore"
      - "**.md"
      - "**.adoc"
      - "*.txt"
      - "docsimg/**"
      - ".ci/jenkins/**"

env:
  GO_VERSION: 1.19

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: End-to-end tests
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Install Go
      id: go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Setup KIND cluster
      uses: engineerd/setup-kind@v0.5.0
      # with:
      #   wait: 300s
      #   version: v0.11.1
      #   image: kindest/node:v1.25.3

    - name: Run tests
      run: |
        make test-e2e
      env:
        KIND_CLUSTER: 'kind'